database:
  host: 'localhost'
  port: 5432
  db: 'bug_tracker'
  user: 'admin'
  password: 'admin'
google:
  secret: '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'
  clientID: '798341407679-s95si1ijre33ju067k657kciif9ots74.apps.googleusercontent.com'
  callback: 'http://localhost:4000/auth/google-redirect'
github:
  clientID: '5afccc5ae0fbbf9ac0cb'
  secret: '94a6d643ccf51036a5c93f0f3384a93f59a85a08'
  callback: 'http://localhost:4000/auth/github-redirect'
app:
  secret: 'McQfTjWmZq4t7w!z4u7x!A%D*F-JaNd'
  session: 'SPX-Fw9cQfTjWmZq4t7w7x!A%WmZq4t'
  port: 4000